export const VN_PARTS = {
  "阿部 有彩": { mae: "1st", ms: "ウラ", main: "1st", ns: "オモテ" },
  "阿部有彩": { mae: "1st", ms: "ウラ", main: "1st", ns: "オモテ" },
  "石井 良磨": { mae: "2nd", ms: "オモテ", main: "2nd", ns: "オモテ" },
  "石井良磨": { mae: "2nd", ms: "オモテ", main: "2nd", ns: "オモテ" },
  "伊藤 有彩": { mae: "2nd", ms: "オモテ", main: "2nd", ns: "オモテ" },
  "伊藤有彩": { mae: "2nd", ms: "オモテ", main: "2nd", ns: "オモテ" },
  "井上 彰": { mae: "2nd", ms: "ウラ", main: "2nd", ns: "ウラ" },
  "井上彰": { mae: "2nd", ms: "ウラ", main: "2nd", ns: "ウラ" },
  "畝田 和": { mae: "1st", ms: "ウラ", main: "1st", ns: "オモテ" },
  "畝田和": { mae: "1st", ms: "ウラ", main: "1st", ns: "オモテ" },
  "大木 菜香": { mae: "1st", ms: "ウラ", main: "2nd", ns: "オモテ" },
  "大木菜香": { mae: "1st", ms: "ウラ", main: "2nd", ns: "オモテ" },
  "大串 美音": { mae: "2nd", ms: "ウラ", main: "2nd", ns: "オモテ" },
  "大串美音": { mae: "2nd", ms: "ウラ", main: "2nd", ns: "オモテ" },
  "奥澤 由弦": { mae: "1st", ms: "オモテ", main: "1st", ns: "ウラ" },
  "奥澤由弦": { mae: "1st", ms: "オモテ", main: "1st", ns: "ウラ" },
  "落合 佑紀": { mae: "2nd", ms: "ウラ", main: "2nd", ns: "ウラ" },
  "落合佑紀": { mae: "2nd", ms: "ウラ", main: "2nd", ns: "ウラ" },
  "尾亦 里彩": { mae: "2nd", ms: "ウラ", main: "2nd", ns: "オモテ" },
  "尾亦里彩": { mae: "2nd", ms: "ウラ", main: "2nd", ns: "オモテ" },
  "金森 結菜": { mae: "1st", ms: "ウラ", main: "1st", ns: "オモテ" },
  "金森結菜": { mae: "1st", ms: "ウラ", main: "1st", ns: "オモテ" },
  "黒瀬 笙子": { mae: "2nd", ms: "ウラ", main: "1st", ns: "オモテ" },
  "黒瀬笙子": { mae: "2nd", ms: "ウラ", main: "1st", ns: "オモテ" },
  "近藤 総司": { mae: "1st", ms: "ウラ", main: "1st", ns: "オモテ" },
  "近藤総司": { mae: "1st", ms: "ウラ", main: "1st", ns: "オモテ" },
  "坂井 詠": { mae: "2nd", ms: "オモテ", main: "2nd", ns: "ウラ" },
  "坂井詠": { mae: "2nd", ms: "オモテ", main: "2nd", ns: "ウラ" },
  "佐々木 達彦": { mae: "1st", ms: "オモテ", main: "1st", ns: "オモテ" },
  "佐々木達彦": { mae: "1st", ms: "オモテ", main: "1st", ns: "オモテ" },
  "佐藤　由梨花": { mae: "1st", ms: "ウラ", main: "1st", ns: "ウラ" },
  "志幸 直人": { mae: "2nd", ms: "ウラ", main: "2nd", ns: "オモテ" },
  "志幸直人": { mae: "2nd", ms: "ウラ", main: "2nd", ns: "オモテ" },
  "清水 優暉": { mae: "1st", ms: "ウラ", main: "1st", ns: "ウラ" },
  "清水優暉": { mae: "1st", ms: "ウラ", main: "1st", ns: "ウラ" },
  "杉田 愛": { mae: "2nd", ms: "オモテ", main: "2nd", ns: "ウラ" },
  "杉田愛": { mae: "2nd", ms: "オモテ", main: "2nd", ns: "ウラ" },
  "杉田 萌": { mae: "1st", ms: "オモテ", main: "1st", ns: "オモテ" },
  "杉田萌": { mae: "1st", ms: "オモテ", main: "1st", ns: "オモテ" },
  "鈴木 颯人": { mae: "1st", ms: "ウラ", main: "2nd", ns: "ウラ" },
  "鈴木颯人": { mae: "1st", ms: "ウラ", main: "2nd", ns: "ウラ" },
  "鈴木 美波": { mae: "2nd", ms: "オモテ", main: "2nd", ns: "ウラ" },
  "鈴木美波": { mae: "2nd", ms: "オモテ", main: "2nd", ns: "ウラ" },
  "高橋 飛羽": { mae: "1st", ms: "オモテ", main: "1st", ns: "ウラ" },
  "高橋飛羽": { mae: "1st", ms: "オモテ", main: "1st", ns: "ウラ" },
  "綱谷 尚": { mae: "2nd", ms: "オモテ", main: "1st", ns: "ウラ" },
  "綱谷尚": { mae: "2nd", ms: "オモテ", main: "1st", ns: "ウラ" },
  "濵中 紗句": { mae: "1st", ms: "オモテ", main: "1st", ns: "オモテ" },
  "濵中紗句": { mae: "1st", ms: "オモテ", main: "1st", ns: "オモテ" },
  "平山 裕祐": { mae: "1st", ms: "オモテ", main: "1st", ns: "ウラ" },
  "平山裕祐": { mae: "1st", ms: "オモテ", main: "1st", ns: "ウラ" },
  "深見 珠央": { mae: "1st", ms: "オモテ", main: "1st", ns: "ウラ" },
  "深見珠央": { mae: "1st", ms: "オモテ", main: "1st", ns: "ウラ" },
  "向井 智春": { mae: "1st", ms: "オモテ", main: "1st", ns: "ウラ" },
  "向井智春": { mae: "1st", ms: "オモテ", main: "1st", ns: "ウラ" },
  "村尾 京香": { mae: "2nd", ms: "ウラ", main: "2nd", ns: "オモテ" },
  "村尾京香": { mae: "2nd", ms: "ウラ", main: "2nd", ns: "オモテ" },
  "渡邊 寛生": { mae: "2nd", ms: "オモテ", main: "2nd", ns: "ウラ" },
  "渡邊寛生": { mae: "2nd", ms: "オモテ", main: "2nd", ns: "ウラ" },
};

export const COLORS = {
  Vn:   {bg:"#0c1f3a",border:"#3b82f6",text:"#93c5fd",badge:"#1d4ed8"},
  Vn1st:{bg:"#0c1f3a",border:"#3b82f6",text:"#93c5fd",badge:"#1d4ed8"},
  Vn2nd:{bg:"#0b2016",border:"#4ade80",text:"#86efac",badge:"#15803d"},
  Va:   {bg:"#14163a",border:"#818cf8",text:"#c7d2fe",badge:"#4338ca"},
  Vc:   {bg:"#180f2e",border:"#a78bfa",text:"#ddd6fe",badge:"#6d28d9"},
  Cb:   {bg:"#1a0b2e",border:"#c084fc",text:"#e9d5ff",badge:"#7e22ce"},
  Fl:   {bg:"#0c2a1a",border:"#34d399",text:"#a7f3d0",badge:"#059669"},
  Ob:   {bg:"#0c2614",border:"#4ade80",text:"#bbf7d0",badge:"#16a34a"},
  Cl:   {bg:"#122610",border:"#86efac",text:"#dcfce7",badge:"#15803d"},
  Fg:   {bg:"#16260c",border:"#a3e635",text:"#ecfccb",badge:"#4d7c0f"},
  Hr:   {bg:"#2a180c",border:"#fb923c",text:"#fed7aa",badge:"#c2410c"},
  Tp:   {bg:"#2a100c",border:"#f87171",text:"#fecaca",badge:"#b91c1c"},
  Tb:   {bg:"#260a0a",border:"#fca5a5",text:"#fee2e2",badge:"#991b1b"},
  Perc: {bg:"#1c1a0c",border:"#fde047",text:"#fef08a",badge:"#a16207"},
  default:{bg:"#141414",border:"#94a3b8",text:"#cbd5e1",badge:"#475569"},
};

export const PART_ORDER=["Vn1st","Vn2nd","Va","Vc","Cb"];

export function getC(part){
  return COLORS[part]||COLORS.default;
}
